# Generated by Django 2.2.5 on 2019-10-22 23:14

from django.db import migrations, models
import django_matplotlib.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompositeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_plot', django_matplotlib.fields.MatplotlibFigureField(verbose_name='Line')),
                ('sine_plot', django_matplotlib.fields.MatplotlibFigureField(verbose_name='Sine')),
                ('imshow_demo', django_matplotlib.fields.MatplotlibFigureField(verbose_name='Image')),
                ('with_args', django_matplotlib.fields.MatplotlibFigureField(verbose_name='Pass args')),
                ('countour_plot', django_matplotlib.fields.MatplotlibFigureField(verbose_name='Contour plot')),
            ],
        ),
    ]
